name: Build Android

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: cat /home/runner/work/pola-flutter/pola-flutter/android/app/google-services.json | base64
    - run: echo ${{ secrets.GOOGLESERVICES }} > /home/runner/work/pola-flutter/pola-flutter/android/app/google-services.json
    - run: flutter build apk --debug
