 name: Build Android

 on:
   push:
   pull_request:

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - uses: subosito/flutter-action@v1
       with:
         channel: 'stable'
     - run: flutter pub get
     - uses: "finnp/create-file-action@master" this step doesn't work
       env:
         FILE_NAME: "/home/runner/work/pola-flutter/pola-flutter/android/app/google-services.json"
         FILE_BASE64: ${{ secrets.GOOGLESERVICES }}
     - run: flutter build apk --debug
