name: Build Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows to trigger the workflow from GitHub

jobs:
    build_android:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true # Speed up the process
            - name: Get dependencies
              run: flutter pub get  
            - name: Create googleservices file
              run: cat /home/runner/work/pola-flutter/pola-flutter/android/app/google-services.json | base64
            - name: Putting secret data
              env:
                DATA: ${{ secrets.GOOGLESERVICES }}
              run: echo $DATA > /home/runner/work/pola-flutter/pola-flutter/android/app/google-services.json
            # - name: Check formatting
            #   run: flutter format --set-exit-if-changed #not working in my computer
            - name: Statically analyze  
              run: flutter analyze
            - name: Widget tests
              run: flutter test
            - name: Build apk
              run: flutter build apk --debug  
