name: Build Android

on:
  push:
  pull_request:
    
jobs:


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        uses: finnp/create-file-action@1.0.0
          env:
            FILE_NAME: "android/app/google-services.json"
            FILE_DATA: ${{ secrets.GOOGLESERVICES }}

      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --debug
